FROM node:22-alpine

WORKDIR /app

# Instala dependências do sistema e do node
RUN apk add --no-cache bash

COPY package*.json ./
RUN npm install

# Copia todo o código para dentro do container
COPY . .

# Expõe a porta padrão do dev server (geralmente 5173 para vite)
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
